server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/sensex
          jwk-set-uri: http://localhost:8085/realms/sensex/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework:
        security: DEBUG